### ISSUE TITLE
Install/config steps missing in the readme?

### ISSUE THREAD

**Issue by tdobbi51** [maen-bn/openamauth#1]
Hello, 

I was very excited to come across an auth package for OpenAM, but I'm not able to get this package to work.   

Auth::attempt() is still authenticating against the laravel database and no requests are sent to OpenAM.  

Here are my steps:
1. Added "maenbn/openamauth": "dev-master" to laravel's composer.json
2. Ran composer install
3. Added 'Maenbn\OpenAmAuth\OpenAmAuthServiceProvider' to laravel's app.conf providers array
4. Ran php artisan vendor:publish
5. Configured appropriate setting in openam.php
6. Edited use statement in user model class to replace Illuminate\Auth\Authenticatable with Maenbn\OpenAmAuth\Authenticatable
7. Created simple OpenAMAuthController 
   
   public function authenticate()
   {
       //Authenticating using user input
       $input = Input::only('uid', 'password');
       if (Auth::attempt($input)) {
           // Authentication passed...
           return redirect("/home");
       }
       else {
           return "FAILED";
       }
   }
   }

Are there install/config steps missing here?  Has this package been tested against the latest version of laravel?
(Testing with laravel 5.1.24)

Sorry, I'm not super experienced with laravel, but do you have any pointers on how I might debug this?  

Thank's for your help.

**Comment by maen-bn** [comment]
Apologies yes there is a step missing and it was me making an assumption on people using the package knowing laravel already. You want to change the value for the 'driver' to 'openam' in config/auth.php.

I'll update the README.md and thanks for using my package. Any problems let me know.

**Comment by tdobbi51** [comment]
That was it.  Thanks for your help.
